-- MySQL Script generated by MySQL Workbench
-- Mon Feb 19 21:19:09 2024
-- Model: rsdb_1    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema rsdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rsdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rsdb` DEFAULT CHARACTER SET utf8mb3 ;
USE `rsdb` ;

-- -----------------------------------------------------
-- Table `rsdb`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rsdb`.`Client` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Surnames` VARCHAR(100) NOT NULL,
  `Born` DATE NULL DEFAULT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Phone` INT NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC) VISIBLE,
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE,
  UNIQUE INDEX `Phone_UNIQUE` (`Phone` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `rsdb`.`Deliver`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rsdb`.`Deliver` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Client_Id` INT NOT NULL,
  `Date` DATE NOT NULL,
  `Date_Deliver` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`Id`, `Client_Id`),
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC) VISIBLE,
  UNIQUE INDEX `Cliente_Id_UNIQUE` (`Client_Id` ASC) VISIBLE,
  INDEX `fk_Pedido_Cliente_idx` (`Client_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_Cliente`
    FOREIGN KEY (`Client_Id`)
    REFERENCES `rsdb`.`Client` (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `rsdb`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rsdb`.`Product` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Brand` VARCHAR(45) NOT NULL,
  `Price` FLOAT NULL DEFAULT NULL,
  `Talla` INT NOT NULL,
  `Color` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `rsdb`.`Deliver_has_Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rsdb`.`Deliver_has_Product` (
  `Deliver_Id` INT NOT NULL,
  `Product_Id` INT NOT NULL,
  `Quantitat` INT NOT NULL,
  PRIMARY KEY (`Deliver_Id`, `Product_Id`),
  INDEX `fk_Pedido_has_Product_Product1_idx` (`Product_Id` ASC) VISIBLE,
  INDEX `fk_Pedido_has_Product_Pedido1_idx` (`Deliver_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_has_Product_Pedido1`
    FOREIGN KEY (`Deliver_Id`)
    REFERENCES `rsdb`.`Deliver` (`Id`),
  CONSTRAINT `fk_Pedido_has_Product_Product1`
    FOREIGN KEY (`Product_Id`)
    REFERENCES `rsdb`.`Product` (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `rsdb`.`Raffle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rsdb`.`Raffle` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Product_Id` INT NOT NULL,
  `Date` DATE NOT NULL,
  `Date_end` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`Id`, `Product_Id`),
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC) VISIBLE,
  INDEX `fk_Raffle_Product1_idx` (`Product_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Raffle_Product1`
    FOREIGN KEY (`Product_Id`)
    REFERENCES `rsdb`.`Product` (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `rsdb`.`Raffle_has_Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rsdb`.`Raffle_has_Client` (
  `Raffle_Id` INT NOT NULL,
  `Client_Id` INT NOT NULL,
  PRIMARY KEY (`Raffle_Id`, `Client_Id`),
  INDEX `fk_Raffle_has_Client_Client1_idx` (`Client_Id` ASC) VISIBLE,
  INDEX `fk_Raffle_has_Client_Raffle1_idx` (`Raffle_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Raffle_has_Client_Client1`
    FOREIGN KEY (`Client_Id`)
    REFERENCES `rsdb`.`Client` (`Id`),
  CONSTRAINT `fk_Raffle_has_Client_Raffle1`
    FOREIGN KEY (`Raffle_Id`)
    REFERENCES `rsdb`.`Raffle` (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `rsdb`.`Carreto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rsdb`.`Carreto` (
  `Client_Id` INT NOT NULL,
  `Product_Id` INT NOT NULL,
  PRIMARY KEY (`Client_Id`, `Product_Id`),
  INDEX `fk_Client_has_Product_Product1_idx` (`Product_Id` ASC) VISIBLE,
  INDEX `fk_Client_has_Product_Client1_idx` (`Client_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Client_has_Product_Client1`
    FOREIGN KEY (`Client_Id`)
    REFERENCES `rsdb`.`Client` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Client_has_Product_Product1`
    FOREIGN KEY (`Product_Id`)
    REFERENCES `rsdb`.`Product` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `rsdb`.`Favoritos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rsdb`.`Favoritos` (
  `Client_Id` INT NOT NULL,
  `Product_Id` INT NOT NULL,
  PRIMARY KEY (`Client_Id`, `Product_Id`),
  INDEX `fk_Client_has_Product_Product2_idx` (`Product_Id` ASC) VISIBLE,
  INDEX `fk_Client_has_Product_Client2_idx` (`Client_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Client_has_Product_Client2`
    FOREIGN KEY (`Client_Id`)
    REFERENCES `rsdb`.`Client` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Client_has_Product_Product2`
    FOREIGN KEY (`Product_Id`)
    REFERENCES `rsdb`.`Product` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
